import { db } from './firebaseConfig';
import { collection, setDoc, doc } from 'firebase/firestore';

// EXPANDED QUESTION BANK - Comprehensive IELTS Speaking Practice Topics
export const initializeExpandedQuestionBanks = async () => {
    const questionBanks = [
        // ====== WORK OR STUDY ======
        {
            topic: 'Work or Study',
            level: 'Band 5-6',
            questions: [
                'Do you work or are you a student?',
                'Why did you choose this kind of work/study?',
                'Do you enjoy your work/study?',
                'What is the most interesting part of your work/study?',
                'What would you like to do in the future?',
                'Do you prefer working alone or with others?',
                'How do you balance work and leisure?',
                'Is your work/study difficult?',
                'What skills have you learned from your work/study?',
                'Would you change your job or field of study in the future?',
                'What time do you usually start work or classes?',
                'Do you have a good relationship with your colleagues/classmates?',
                'What do you do during your lunch break?',
                'How do you commute to work or school?',
                'What subjects do you find most challenging?',
                'Do you think your job/study is important for society?',
                'How has your work/study changed over the years?',
                'What advice would you give to someone starting in your field?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Work or Study',
            level: 'Band 6-7',
            questions: [
                'What are the main responsibilities in your current job/studies?',
                'How do you think your field will evolve in the next decade?',
                'What are the biggest challenges facing your industry/academic field?',
                'How do you stay updated with developments in your area of expertise?',
                'What role does technology play in your work/studies?',
                'How do you measure success in your career/academic pursuits?',
                'What would you say are the essential qualities for success in your field?',
                'How has globalization affected your industry/area of study?',
                'What are the ethical considerations in your work/field of study?',
                'How do you see the work-life balance changing in modern society?',
                'What innovations have had the most impact on your profession?',
                'How important is continuous learning in your career?',
                'What are the prospects for young people entering your field?',
                'How do cultural differences affect international business/academic collaboration?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Work or Study',
            level: 'Band 7-8',
            questions: [
                'Analyze the paradigm shifts that have transformed your profession over the past generation.',
                'How do you reconcile the competing demands of specialization and interdisciplinary collaboration?',
                'What are the implications of artificial intelligence and automation for future employment patterns?',
                'How should educational institutions adapt to prepare students for an increasingly volatile job market?',
                'Evaluate the role of mentorship and professional networks in career advancement.',
                'How do you think remote work will fundamentally alter organizational structures?',
                'What are the psychological and sociological impacts of the gig economy?',
                'How can professionals maintain authenticity while adapting to changing workplace cultures?',
                'What ethical frameworks should guide decision-making in your field?',
                'How do you envision the intersection of sustainability and profitability in future business models?',
            ],
            createdAt: new Date(),
        },

        // ====== DAILY ROUTINE & FREE TIME ======
        {
            topic: 'Daily Routine & Free Time',
            level: 'Band 5-6',
            questions: [
                'What is your daily routine like?',
                'How do you spend your free time?',
                'Do you prefer relaxing at home or going out in your free time?',
                'What do you usually do after work or school?',
                'How much free time do you have each day?',
                'Do you think it\'s important to have a routine?',
                'How has your routine changed recently?',
                'What would you like to do if you had more free time?',
                'Do you plan your free time or just relax?',
                'What activities help you relax?',
                'What time do you usually wake up and go to bed?',
                'Do you have any hobbies?',
                'How do you spend your weekends?',
                'Do you prefer indoor or outdoor activities?',
                'What do you do to stay entertained?',
                'Do you like to try new activities?',
                'How often do you meet friends in your free time?',
                'Do you think people have enough free time nowadays?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Daily Routine & Free Time',
            level: 'Band 6-7',
            questions: [
                'How do you prioritize different activities in your daily schedule?',
                'What factors influence how you choose to spend your leisure time?',
                'How has technology changed the way people spend their free time?',
                'Do you think work-life balance is achievable in modern society?',
                'How do cultural factors influence daily routines in your country?',
                'What are the benefits and drawbacks of having a structured routine?',
                'How do you adapt your routine when circumstances change?',
                'What role does physical exercise play in your daily life?',
                'How do you manage stress and maintain well-being in your routine?',
                'What trends do you see in how people spend their leisure time?',
                'How important is spontaneity versus planning in daily life?',
                'What impact does social media have on how people use their free time?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Daily Routine & Free Time',
            level: 'Band 7-8',
            questions: [
                'How do societal expectations and individual autonomy intersect in shaping daily routines?',
                'What are the psychological implications of the increasing blurring of work and personal time?',
                'How do you think the concept of leisure will evolve as societies become more automated?',
                'Analyze the relationship between routine, creativity, and personal fulfillment.',
                'How do economic inequalities manifest in people\'s access to meaningful leisure activities?',
                'What role should governments play in ensuring citizens have adequate time for rest and recreation?',
                'How do different philosophical approaches to time management reflect cultural values?',
                'What are the implications of the "always-on" culture for mental health and social relationships?',
            ],
            createdAt: new Date(),
        },

        // ====== TECHNOLOGY & MOBILE PHONES ======
        {
            topic: 'Technology & Mobile Phones',
            level: 'Band 5-6',
            questions: [
                'How often do you use technology?',
                'What technology do you use most often?',
                'Do you think technology makes life easier?',
                'How do you use your mobile phone?',
                'Could you live without your mobile phone?',
                'What are the advantages of smartphones?',
                'Are there any disadvantages to using technology?',
                'How has technology changed the way we communicate?',
                'Do you use technology for studying or working?',
                'What new technology would you like to have?',
                'Do you prefer to buy things online or in stores?',
                'How do you learn to use new technology?',
                'Do you think children spend too much time on technology?',
                'What was life like before smartphones?',
                'Do you use social media? How often?',
                'Have you ever had problems with technology?',
                'Do you think technology is changing too fast?',
                'What apps do you use most on your phone?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Technology & Mobile Phones',
            level: 'Band 6-7',
            questions: [
                'How has the digital divide affected different generations and social groups?',
                'What are the privacy implications of increasing digital connectivity?',
                'How do you think artificial intelligence will impact daily life?',
                'What role does technology play in education and learning?',
                'How has e-commerce changed consumer behavior and business models?',
                'What are the environmental impacts of rapid technological advancement?',
                'How do you balance the benefits and risks of social media use?',
                'What cybersecurity challenges do individuals and organizations face?',
                'How has technology influenced political engagement and democratic processes?',
                'What ethical considerations arise from data collection and algorithmic decision-making?',
                'How do cultural differences affect technology adoption and use?',
                'What skills will be most important in an increasingly digital world?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Technology & Mobile Phones',
            level: 'Band 7-8',
            questions: [
                'How might the metaverse and virtual reality reshape social interaction and human experience?',
                'What are the philosophical implications of human-AI collaboration and potential consciousness in machines?',
                'Analyze the tension between technological innovation and data sovereignty in the global economy.',
                'How should societies navigate the ethical complexities of genetic engineering and biotechnology?',
                'What frameworks can help us evaluate the long-term societal impacts of emerging technologies?',
                'How might quantum computing revolutionize problem-solving across different domains?',
                'What are the implications of technological singularity theories for human agency and purpose?',
                'How can democratic institutions adapt to govern rapidly evolving technological landscapes?',
            ],
            createdAt: new Date(),
        },

        // ====== HEALTH & FITNESS ======
        {
            topic: 'Health & Fitness',
            level: 'Band 5-6',
            questions: [
                'How do you keep healthy?',
                'Do you do any sports or exercise?',
                'What do you think is the best way to stay fit?',
                'Do you pay attention to your diet?',
                'How often do you exercise?',
                'Is it easy to keep fit in your country?',
                'What are popular sports in your country?',
                'Have your health habits changed recently?',
                'Do you prefer exercising alone or with others?',
                'What advice would you give to someone who wants to be healthier?',
                'Do you ever feel stressed? How do you deal with it?',
                'How many hours of sleep do you usually get?',
                'Do you take any vitamins or supplements?',
                'Have you ever been on a diet?',
                'Do you think mental health is as important as physical health?',
                'What unhealthy habits do you think people should avoid?',
                'Do you prefer home-cooked meals or eating out?',
                'How do you stay motivated to exercise?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Health & Fitness',
            level: 'Band 6-7',
            questions: [
                'How do socioeconomic factors influence access to healthcare and healthy lifestyle choices?',
                'What role should governments play in promoting public health initiatives?',
                'How has the understanding of mental health evolved in recent decades?',
                'What are the challenges of maintaining work-life balance for optimal health?',
                'How do cultural attitudes toward body image and fitness vary globally?',
                'What impact has the COVID-19 pandemic had on health awareness and behaviors?',
                'How can communities create environments that promote healthier living?',
                'What are the pros and cons of alternative and complementary medicine?',
                'How does aging population demographics affect healthcare systems?',
                'What role does preventive care play in reducing healthcare costs?',
                'How do environmental factors influence public health outcomes?',
                'What ethical issues arise in modern medical practice and research?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Health & Fitness',
            level: 'Band 7-8',
            questions: [
                'How should healthcare systems balance individual choice with collective public health responsibilities?',
                'What are the bioethical implications of genetic screening and personalized medicine?',
                'Analyze the complex relationship between mental health, social inequality, and systemic change.',
                'How might advances in neuroscience challenge our understanding of free will and personal responsibility for health choices?',
                'What frameworks should guide resource allocation in healthcare during times of scarcity?',
                'How do we reconcile traditional healing practices with evidence-based medicine in multicultural societies?',
                'What are the long-term implications of pharmaceutical dependency and antibiotic resistance?',
                'How should societies address the ethical complexities of end-of-life care and assisted dying?',
            ],
            createdAt: new Date(),
        },

        // ====== TRAVEL & HOLIDAYS ======
        {
            topic: 'Travel & Holidays',
            level: 'Band 5-6',
            questions: [
                'Do you like to travel?',
                'Where do you usually go on holiday?',
                'Why do you like going there?',
                'What do you like to do on holiday?',
                'Do you prefer traveling alone or with others?',
                'What is your dream holiday destination?',
                'How do you usually prepare for a trip?',
                'Have you ever had any problems while traveling?',
                'Do you think holidays are important? Why?',
                'What was your most memorable holiday?',
                'Do you prefer beach holidays or city breaks?',
                'How do you choose where to go on vacation?',
                'Do you like trying local food when you travel?',
                'Have you ever traveled to another country?',
                'Do you take many photos when you travel?',
                'What do you pack when you go on a trip?',
                'Do you prefer planning trips or being spontaneous?',
                'How often do you go on holiday?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Travel & Holidays',
            level: 'Band 6-7',
            questions: [
                'How has tourism impacted local communities and environments in popular destinations?',
                'What are the benefits and drawbacks of overtourism in major cities?',
                'How do you think travel broadens people\'s perspectives and cultural understanding?',
                'What role does sustainable tourism play in protecting natural and cultural heritage?',
                'How has technology changed the way people plan and experience travel?',
                'What are the economic implications of the tourism industry for developing countries?',
                'How do visa requirements and border controls affect global mobility?',
                'What impact has the pandemic had on travel patterns and the tourism industry?',
                'How do different forms of accommodation (hotels, homestays, etc.) offer different travel experiences?',
                'What ethical considerations should travelers keep in mind when visiting other cultures?',
                'How does mass tourism differ from responsible or eco-tourism?',
                'What role do travel documentaries and social media play in shaping travel desires?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Travel & Holidays',
            level: 'Band 7-8',
            questions: [
                'How do we balance the human desire for exploration with environmental sustainability and climate concerns?',
                'What are the neo-colonial implications of certain forms of tourism in developing regions?',
                'How might virtual reality and digital experiences reshape the concept of travel and cultural exchange?',
                'Analyze the tension between preserving authentic cultural experiences and meeting tourist expectations.',
                'What philosophical questions arise from the commodification of cultural heritage for tourism?',
                'How do patterns of global mobility reflect and reinforce existing inequalities between nations?',
                'What role should international organizations play in regulating tourism\'s environmental and social impacts?',
                'How might climate change fundamentally alter global tourism patterns and destinations?',
            ],
            createdAt: new Date(),
        },

        // ====== ENVIRONMENT & NATURE ======
        {
            topic: 'Environment & Nature',
            level: 'Band 5-6',
            questions: [
                'Do you like spending time in nature?',
                'What is the environment like in your hometown?',
                'Are there any environmental problems in your country?',
                'What can people do to protect the environment?',
                'Do you recycle at home?',
                'How can we encourage people to care for nature?',
                'Have you ever participated in an environmental project?',
                'What is your favorite natural place?',
                'Do you think environmental education is important?',
                'How has the environment changed in recent years?',
                'Do you try to save energy at home?',
                'What do you think about electric cars?',
                'Is pollution a problem in your city?',
                'Do you buy organic food?',
                'How do you reduce waste in your daily life?',
                'Do you prefer natural or urban environments?',
                'What animals or plants are common in your area?',
                'Do you think climate change is a serious problem?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Environment & Nature',
            level: 'Band 6-7',
            questions: [
                'How can individuals balance personal convenience with environmental responsibility?',
                'What role should governments play in addressing climate change and environmental degradation?',
                'How do economic interests conflict with environmental protection efforts?',
                'What are the most effective strategies for promoting sustainable development?',
                'How has urbanization affected local ecosystems and biodiversity?',
                'What impact do multinational corporations have on global environmental issues?',
                'How can education systems better prepare citizens for environmental challenges?',
                'What are the social justice implications of environmental problems?',
                'How do different cultures approach the relationship between humans and nature?',
                'What technological solutions show promise for addressing environmental issues?',
                'How can communities become more resilient to climate change effects?',
                'What are the challenges of transitioning to renewable energy sources?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Environment & Nature',
            level: 'Band 7-8',
            questions: [
                'How do we reconcile anthropocentric worldviews with the intrinsic rights of natural ecosystems?',
                'What are the ethical implications of geoengineering as a response to climate change?',
                'How should intergenerational justice influence contemporary environmental policy decisions?',
                'Analyze the paradox of growth-dependent economic systems in a finite ecological world.',
                'What role should indigenous knowledge systems play in addressing global environmental crises?',
                'How might the concept of planetary boundaries reshape international governance structures?',
                'What are the implications of treating nature as a legal entity with rights?',
                'How do we navigate the tension between immediate human needs and long-term planetary health?',
            ],
            createdAt: new Date(),
        },

        // ====== NEW TOPICS ======

        // ====== FOOD & COOKING ======
        {
            topic: 'Food & Cooking',
            level: 'Band 5-6',
            questions: [
                'What is your favorite type of food?',
                'Do you like cooking? Why or why not?',
                'What do you usually eat for breakfast?',
                'Do you prefer eating at home or in restaurants?',
                'Have you ever tried food from other countries?',
                'What foods are popular in your country?',
                'Do you think fast food is unhealthy?',
                'How often do you eat with your family?',
                'What cooking skills do you have?',
                'Do you grow any of your own food?',
                'What\'s your favorite restaurant?',
                'Do you have any foods you dislike?',
                'How important are family meals in your culture?',
                'Do you read recipes or cook by instinct?',
                'What kitchen equipment is most useful?',
                'Have your eating habits changed over the years?',
                'Do you enjoy trying new foods?',
                'What would you cook for a special occasion?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Food & Cooking',
            level: 'Band 6-7',
            questions: [
                'How do food traditions reflect cultural identity and heritage?',
                'What are the implications of industrial agriculture for food quality and sustainability?',
                'How has globalization affected local food systems and culinary traditions?',
                'What role does food play in social bonding and community building?',
                'How do economic factors influence people\'s dietary choices?',
                'What are the environmental impacts of different dietary patterns?',
                'How has the farm-to-table movement changed consumer attitudes toward food?',
                'What challenges do urban areas face in ensuring food security?',
                'How do food regulations balance safety with cultural food practices?',
                'What impact has social media had on food culture and trends?',
                'How can education promote better understanding of nutrition and cooking skills?',
                'What ethical considerations arise from different approaches to animal agriculture?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Food & Cooking',
            level: 'Band 7-8',
            questions: [
                'How do food systems intersect with issues of social justice, labor rights, and economic inequality?',
                'What are the philosophical and ethical dimensions of different dietary choices in contemporary society?',
                'How might climate change fundamentally alter global food production and consumption patterns?',
                'Analyze the tension between food sovereignty movements and global trade liberalization.',
                'What are the implications of genetic modification and biotechnology for future food security?',
                'How do we balance cultural food traditions with evolving understanding of nutrition and sustainability?',
                'What role should governments play in regulating food marketing and addressing obesity epidemics?',
                'How might alternative protein sources challenge traditional concepts of food and eating?',
            ],
            createdAt: new Date(),
        },

        // ====== FAMILY & RELATIONSHIPS ======
        {
            topic: 'Family & Relationships',
            level: 'Band 5-6',
            questions: [
                'Tell me about your family.',
                'How often do you see your family members?',
                'What do you like doing with your family?',
                'Are you close to your parents?',
                'Do you have any brothers or sisters?',
                'What family traditions do you celebrate?',
                'How has your family influenced your life?',
                'Do you prefer spending time with family or friends?',
                'What qualities make a good friend?',
                'How do you make new friends?',
                'Do you keep in touch with childhood friends?',
                'What do you do when you have disagreements with family?',
                'How important is family support in your life?',
                'Do you think family relationships are changing?',
                'What role do grandparents play in your family?',
                'How do you show appreciation to your family?',
                'What family values are important to you?',
                'Do you plan to have a family of your own?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Family & Relationships',
            level: 'Band 6-7',
            questions: [
                'How are family structures evolving in modern society?',
                'What challenges do families face in maintaining close relationships today?',
                'How do cultural differences affect family dynamics and expectations?',
                'What role does technology play in family communication and relationships?',
                'How do economic pressures impact family life and relationships?',
                'What are the benefits and challenges of extended vs. nuclear family systems?',
                'How do different generations within families navigate changing social values?',
                'What factors contribute to successful long-term relationships?',
                'How has the concept of marriage evolved in contemporary society?',
                'What support systems exist for families facing difficulties?',
                'How do work-life balance issues affect family relationships?',
                'What role do friends play compared to family in providing emotional support?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Family & Relationships',
            level: 'Band 7-8',
            questions: [
                'How do societal changes in gender roles reshape family dynamics and relationship expectations?',
                'What are the psychological and social implications of declining birth rates in developed societies?',
                'How do we balance individual autonomy with family obligations and cultural expectations?',
                'What ethical considerations arise from assisted reproductive technologies and changing family formations?',
                'How might concepts of kinship and family evolve with increasing global mobility and digital connectivity?',
                'What role should institutions play in supporting diverse family structures and relationship models?',
                'How do attachment theories and childhood experiences influence adult relationship patterns?',
                'What are the implications of increasing life expectancy for intergenerational family relationships?',
            ],
            createdAt: new Date(),
        },

        // ====== EDUCATION & LEARNING ======
        {
            topic: 'Education & Learning',
            level: 'Band 5-6',
            questions: [
                'What subjects did you enjoy most at school?',
                'Do you think education is important? Why?',
                'How do you prefer to learn new things?',
                'What was your favorite teacher like?',
                'Do you think online learning is effective?',
                'What skills would you like to learn in the future?',
                'How has technology changed education?',
                'Do you think exams are a good way to test knowledge?',
                'What makes a good student?',
                'How do you stay motivated when learning something difficult?',
                'Do you prefer learning alone or in groups?',
                'What educational opportunities exist in your country?',
                'How important is practical experience compared to theoretical knowledge?',
                'What advice would you give to someone struggling with their studies?',
                'Do you think education should be free for everyone?',
                'How do you think schools could be improved?',
                'What role do parents play in their children\'s education?',
                'Is lifelong learning important in today\'s world?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Education & Learning',
            level: 'Band 6-7',
            questions: [
                'How should educational systems adapt to prepare students for rapidly changing job markets?',
                'What are the benefits and drawbacks of standardized testing and curriculum?',
                'How can education systems address inequality and provide equal opportunities for all students?',
                'What role should critical thinking and creativity play in modern education?',
                'How has digitalization transformed learning opportunities and challenges?',
                'What are the implications of rising education costs for social mobility?',
                'How do different pedagogical approaches affect student learning outcomes?',
                'What skills and knowledge will be most valuable in the future economy?',
                'How can education systems better support students with diverse learning needs?',
                'What role should vocational training play alongside academic education?',
                'How do cultural attitudes toward education vary globally?',
                'What are the challenges and opportunities of internationalization in education?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Education & Learning',
            level: 'Band 7-8',
            questions: [
                'How do epistemological frameworks influence what knowledge is considered legitimate in educational contexts?',
                'What are the implications of artificial intelligence for personalized learning and educational assessment?',
                'How should educational institutions balance market demands with humanistic educational ideals?',
                'What role should education play in addressing social inequality and promoting democratic citizenship?',
                'How might neuroscientific insights about learning reshape pedagogical practices and educational structures?',
                'What are the ethical implications of educational data collection and algorithmic decision-making in schools?',
                'How do we reconcile local cultural knowledge with global educational standards and practices?',
                'What frameworks can help evaluate the long-term societal impact of different educational philosophies?',
            ],
            createdAt: new Date(),
        },

        // ====== MEDIA & ENTERTAINMENT ======
        {
            topic: 'Media & Entertainment',
            level: 'Band 5-6',
            questions: [
                'What types of movies do you enjoy watching?',
                'Do you prefer watching TV or reading books?',
                'How do you usually find out about news and current events?',
                'What music do you like to listen to?',
                'Do you play any musical instruments?',
                'How often do you use social media?',
                'What\'s your favorite way to relax and be entertained?',
                'Do you like going to concerts or live performances?',
                'Have you ever been influenced by something you saw in the media?',
                'Do you think there\'s too much violence in movies and TV?',
                'What was the last book you read?',
                'Do you prefer comedy or drama?',
                'How has streaming changed the way people watch entertainment?',
                'Do you think celebrities have too much influence on society?',
                'What kind of content do you share on social media?',
                'Do you follow any news sources regularly?',
                'What entertains children differently than adults?',
                'How do you choose what to watch or read?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Media & Entertainment',
            level: 'Band 6-7',
            questions: [
                'How has the rise of streaming platforms affected traditional media industries?',
                'What role does media play in shaping public opinion and political discourse?',
                'How do algorithmic recommendations influence our entertainment choices and cultural exposure?',
                'What are the implications of media consolidation for diversity of content and perspectives?',
                'How has social media changed the relationship between celebrities and their audiences?',
                'What ethical responsibilities do media companies have toward their audiences?',
                'How do different cultures approach censorship and content regulation?',
                'What impact has user-generated content had on traditional media gatekeepers?',
                'How can consumers develop critical media literacy skills?',
                'What are the psychological effects of constant media consumption?',
                'How has globalization affected local media and entertainment industries?',
                'What role should public media play in democratic societies?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Media & Entertainment',
            level: 'Band 7-8',
            questions: [
                'How do media representations construct and reinforce social identities and power structures?',
                'What are the implications of deepfakes and synthetic media for truth, authenticity, and social trust?',
                'How might immersive technologies fundamentally alter the nature of storytelling and audience engagement?',
                'Analyze the tension between free expression and platform responsibility in digital media ecosystems.',
                'What are the philosophical implications of algorithm-curated reality and filter bubbles for human agency?',
                'How do media industries navigate the balance between artistic integrity and commercial viability?',
                'What role should media play in preserving cultural heritage while fostering innovation and change?',
                'How might blockchain and decentralized technologies reshape media ownership and distribution models?',
            ],
            createdAt: new Date(),
        },

        // ====== TRANSPORTATION & CITIES ======
        {
            topic: 'Transportation & Cities',
            level: 'Band 5-6',
            questions: [
                'How do you usually get around your city?',
                'Do you prefer public transportation or driving?',
                'What are the traffic problems in your area?',
                'Have you ever lived in a different city?',
                'What do you like most about your hometown?',
                'Do you think cities are getting too crowded?',
                'What makes a city a good place to live?',
                'Do you prefer city life or country life?',
                'How has your city changed over the years?',
                'What transportation improvements would you like to see?',
                'Do you think electric vehicles are the future?',
                'How important is public transportation in your city?',
                'What are the advantages of living in a big city?',
                'Do you walk or cycle much in your daily life?',
                'What problems do cities face today?',
                'How do you think cities will look in the future?',
                'What\'s the best way to reduce traffic congestion?',
                'Do you think ride-sharing apps are useful?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Transportation & Cities',
            level: 'Band 6-7',
            questions: [
                'How can urban planning balance economic development with livability and sustainability?',
                'What are the challenges and benefits of transitioning to electric and autonomous vehicles?',
                'How do transportation systems affect social equity and access to opportunities?',
                'What strategies can cities use to reduce their environmental footprint?',
                'How has the pandemic changed urban mobility patterns and city planning priorities?',
                'What role should citizen participation play in urban development decisions?',
                'How can cities accommodate population growth while maintaining quality of life?',
                'What are the implications of smart city technologies for privacy and governance?',
                'How do housing costs and urban gentrification affect community demographics?',
                'What innovative transportation solutions are being developed for urban areas?',
                'How can cities become more resilient to climate change and natural disasters?',
                'What are the trade-offs between urban density and suburban sprawl?',
            ],
            createdAt: new Date(),
        },
        {
            topic: 'Transportation & Cities',
            level: 'Band 7-8',
            questions: [
                'How do we reconcile individual mobility desires with collective environmental and social responsibilities?',
                'What are the implications of autonomous vehicles for urban space allocation, employment, and social interaction?',
                'How might concepts of citizenship and belonging evolve in increasingly mobile and connected urban populations?',
                'Analyze the tension between efficient urban systems and human-scale community development.',
                'What ethical frameworks should guide the deployment of surveillance technologies in smart cities?',
                'How do global migration patterns and urbanization trends reshape concepts of place and identity?',
                'What role should cities play as actors in addressing transnational challenges like climate change?',
                'How might virtual reality and remote work fundamentally alter the function and form of cities?',
            ],
            createdAt: new Date(),
        },
    ];

    try {
        const questionsRef = collection(db, 'questions');
        for (const bank of questionBanks) {
            // Create document ID combining topic and level for better organization
            const docId = `${bank.topic}_${bank.level}`.replace(/\s+/g, '_');
            await setDoc(doc(questionsRef, docId), bank);
            console.log(`Added/updated question bank for ${bank.topic} - ${bank.level}`);
        }
        console.log('✅ EXPANDED Question banks initialized successfully!');
        console.log(`📚 Total question banks: ${questionBanks.length}`);
        console.log(`🎯 Topics covered: ${[...new Set(questionBanks.map(bank => bank.topic))].length}`);
        console.log(`📈 Difficulty levels: ${[...new Set(questionBanks.map(bank => bank.level))].length}`);
    } catch (error) {
        console.error('❌ Error initializing expanded question banks:', error.message);
    }
};